# Generated by Django 5.0.2 on 2024-03-22 19:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_product_onsale_product_salepercent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='salePercent',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
